# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
language: python
python: 3.5

compiler:
  - gcc
os:
  - linux

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=pypy

# install patched librdkafka version
before_install:
  - mkdir ~/librdkafka
  - curl -sL https://github.com/authbox/librdkafka/archive/5576b5a928e079518cd049234963f5b7c599c58d.tar.gz | tar -C ~/librdkafka --strip-components=1 -xz
  - (cd ~/librdkafka && ./configure && make && sudo make install)

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}


